/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obed77;

import BaseDeDatos.ConexionBD;
import com.sun.awt.AWTUtilities;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asiel 77
 */
public class Validación extends javax.swing.JFrame {
Shape shape = null;
    /**
     * Creates new form Validación
     */
    public Validación() {
        initComponents();
        shape = new RoundRectangle2D.Float(0,0,this.getWidth(),this.getHeight(),20,20);
        AWTUtilities.setWindowShape(this, shape);
    }
    
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/LogoObed77.png"));


        return retValue;
    }
    void inicio()
    {
    try {
        String user = txt_user.getText();
        char[] cpass = txt_pass.getPassword();
        String pass = String.valueOf(cpass);
        
        ConexionBD parametros = new ConexionBD();
        Class.forName(parametros.getDriver());
        Connection con = DriverManager.getConnection(parametros.getUrl(), parametros.getUser(), parametros.getPass());
        String sql = "SELECT * FROM usuarios WHERE usuarios.usuario='"+user+"' AND usuarios.pass='"+pass+"'";
        Statement st= con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        ResultSet  rs = st.executeQuery(sql);
        boolean f;
        f = rs.next();
        
        if (f)
        {
            Principal pc = new Principal();
            pc.setExtendedState(MAXIMIZED_BOTH);
            pc.setVisible(true);
            this.dispose();
        }else
        {
            JOptionPane.showMessageDialog(this,"Usuario o Contraseña Incorrectos", "Error",1,null);
        }
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Validación.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Validación.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_aceptar1 = new javax.swing.JButton();
        btn_aceptar2 = new javax.swing.JButton();
        txt_pass = new org.edisoncor.gui.passwordField.PasswordFieldRound();
        txt_user = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);

        panelCurves1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicioimagen.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setIconTextGap(0);
        panelCurves1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 190, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LabelPASS.png"))); // NOI18N
        panelCurves1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Labelusuario.png"))); // NOI18N
        panelCurves1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 20));

        btn_aceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_logout1.png"))); // NOI18N
        btn_aceptar1.setText("    Salir");
        btn_aceptar1.setToolTipText("");
        btn_aceptar1.setBorder(null);
        btn_aceptar1.setBorderPainted(false);
        btn_aceptar1.setContentAreaFilled(false);
        btn_aceptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_aceptar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_aceptar1.setIconTextGap(-3);
        btn_aceptar1.setMaximumSize(new java.awt.Dimension(45, 57));
        btn_aceptar1.setMinimumSize(new java.awt.Dimension(45, 57));
        btn_aceptar1.setPreferredSize(new java.awt.Dimension(45, 57));
        btn_aceptar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_logout1.png"))); // NOI18N
        btn_aceptar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_logout2.png"))); // NOI18N
        btn_aceptar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_aceptar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptar1ActionPerformed(evt);
            }
        });
        panelCurves1.add(btn_aceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, 70));

        btn_aceptar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_login1.png"))); // NOI18N
        btn_aceptar2.setText("Ingresar");
        btn_aceptar2.setToolTipText("");
        btn_aceptar2.setBorder(null);
        btn_aceptar2.setBorderPainted(false);
        btn_aceptar2.setContentAreaFilled(false);
        btn_aceptar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_aceptar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_aceptar2.setIconTextGap(-3);
        btn_aceptar2.setMaximumSize(new java.awt.Dimension(45, 57));
        btn_aceptar2.setMinimumSize(new java.awt.Dimension(45, 57));
        btn_aceptar2.setPreferredSize(new java.awt.Dimension(45, 57));
        btn_aceptar2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_login1.png"))); // NOI18N
        btn_aceptar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_login2.png"))); // NOI18N
        btn_aceptar2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_aceptar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_aceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptar2ActionPerformed(evt);
            }
        });
        panelCurves1.add(btn_aceptar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 70, 70));

        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });
        panelCurves1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 150, 25));

        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userKeyPressed(evt);
            }
        });
        panelCurves1.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 150, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInsertar800x600.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptar1ActionPerformed
        
        
        int opc = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (opc == 0) {
            System.exit(0);
        }
                  // TODO add your handling code here:
    }//GEN-LAST:event_btn_aceptar1ActionPerformed

    private void btn_aceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptar2ActionPerformed
        String user = txt_user.getText();
        char[] cpass = txt_pass.getPassword();
        String pass = String.valueOf(cpass);
        
        if (user.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Ingrese un usuario", "Error",1,null);
            txt_user.requestFocus();
        }else
        {
            if(pass.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Ingrese la contraseña", "Error",1,null);
                txt_pass.requestFocus();
            }else
        {
              inicio();    
        }
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_btn_aceptar2ActionPerformed

    private void txt_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyPressed
String user = txt_user.getText();
        char[] cpass = txt_pass.getPassword();
        String pass = String.valueOf(cpass);         
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              if (user.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Ingrese un usuario", "Error",1,null);
            txt_user.requestFocus();
        }else
        {
            if(pass.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Ingrese la contraseña", "Error",1,null);
                txt_pass.requestFocus();
            }else
        {
              inicio();    
        }
        }
          }         // TODO add your handling code here:
    }//GEN-LAST:event_txt_userKeyPressed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
String user = txt_user.getText();
        char[] cpass = txt_pass.getPassword();
        String pass = String.valueOf(cpass);         
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              if (user.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Ingrese un usuario", "Error",1,null);
            txt_user.requestFocus();
        }else
        {
            if(pass.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Ingrese la contraseña", "Error",1,null);
                txt_pass.requestFocus();
            }else
        {
              inicio();    
        }
        }
          }         // TODO add your handling code here:
    }//GEN-LAST:event_txt_passKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Validación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Validación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Validación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Validación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Validación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar1;
    private javax.swing.JButton btn_aceptar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.passwordField.PasswordFieldRound txt_pass;
    private org.edisoncor.gui.textField.TextFieldRound txt_user;
    // End of variables declaration//GEN-END:variables
}
